
/** Required package class namespace */
package computerscience30s;

/**
 * Graphics1.java - this is a form (or frame, or 'container', or user interface)
 * built using the NetBeans WYSIWYG ("what you see is what you get") UI 
 * designer. To make this type of JFrame, you go to "File -> New File" and  
 * select "JFrame Form" and the UI editor will appear. To switch between code  
 * and the designer, use the buttons under the "Graphics2.java" tab named 
 * "Source" and "Design". We will be using the editor's "Palette" and 
 * "Properties" windows to build and change the design and then adding code as 
 * needed. We will examine this frame and Graphics1 to compare doing the same 
 * things using a designer vs. writing all the code ourselves. 
 * 
 * NOTE: For those students who took the introductory Computer Science 20S 
 * course and used Visual Studio and the C# programming language, an editor 
 * like this should seem familiar to you. That IDE allows programmers to use
 * the WYSIWYG editor without having to write all the code. Editors just write 
 * code for you (both Visual Studio and this NetBeans editor) and "hide" that 
 * code (either in a collapsed method in NetBeans, or in another class in 
 * Visual studio). You can find a Visual Studio C# version of this example
 * here: https://bit.ly/4k5ccfN with the specific code page here:
 * https://bit.ly/3SzFK9n
 * 
 * NOTE: If you remember having to "name" all the objects in Visual
 * Studio, you can also do this in NetBeans (although in this course that is not 
 * required) by right clicking on each object and selecting "Change Variable
 * Name..." and then typing in a new name. 
 *
 * @author Mr. Wachs
 * @since December 2025
 */
public class Graphics1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Graphics1.class.getName());

    /**
     * Creates new form Graphics1
     */
    public Graphics1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Graphics1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
