
/** Required package class namespace */
package computerscience30s;

/**
 * Graphics1.java - this is a form (or frame, or 'container', or user interface)
 * built using the NetBeans WYSIWYG ("what you see is what you get") UI 
 * designer. To make this type of JFrame, you go to "File -> New File" and  
 * select "JFrame Form" and the UI editor will appear. To switch between code  
 * and the designer, use the buttons under the "Graphics2.java" tab named 
 * "Source" and "Design". We will be using the editor's "Palette" and 
 * "Properties" windows to build and change the design and then adding code as 
 * needed. We will examine this frame and Graphics1 to compare doing the same 
 * things using a designer vs. writing all the code ourselves. 
 * 
 * NOTE: For those students who took the introductory Computer Science 20S 
 * course and used Visual Studio and the C# programming language, an editor 
 * like this should seem familiar to you. That IDE allows programmers to use
 * the WYSIWYG editor without having to write all the code. Editors just write 
 * code for you (both Visual Studio and this NetBeans editor) and "hide" that 
 * code (either in a collapsed method in NetBeans, or in another class in 
 * Visual studio). You can find a Visual Studio C# version of this example
 * here: https://bit.ly/4k5ccfN with the specific code page here:
 * https://bit.ly/3SzFK9n
 * 
 * NOTE: If you remember having to "name" all the objects in Visual
 * Studio, you can also do this in NetBeans (although in this course that is not 
 * required) by right clicking on each object and selecting "Change Variable
 * Name..." and then typing in a new name. 
 *
 * @author Mr. Wachs
 * @since December 2025
 */
public class Graphics1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Graphics1.class.getName());

    /**
     * Creates new form Graphics1
     */
    public Graphics1() {
        initComponents();
        
        // Add code after the call to the method in the line above (which do 
        // not erase that line - which is a method call) - now add code to   
        // make the form (frame, container, window, etc.) appear to the user
        // and other methods we can call to make visual changes...
            
        // Some properties could be coded and others can be set using the
        // properties window in the designer
        
        // When designing, another option that could be done is to "right click"
        // on the frame (the "container") and select "Set Layout" and then 
        // select "null" - this give you more control over where items can be 
        // placed but requires you to use code to set the size of the frame
        // before it is shown...
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hello World");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jLabel1.setText("Good-bye World");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    ////////////////////////////////////////////////////////////////////////////
    // NOTE: the NetBeans WYSIWYG visual designer also adds a version of the 
    // "main" method to this class of code (each JFrame form when added also 
    // adds a main method below for each JFrame form seen below - just like the 
    // original class file when you build a project). You can certainly delete
    // that original project class file, and then the project will use this 
    // version of main when the project runs (when you click the green tirangle 
    // above on the NetBeans toolbar) or you can delete the main method below 
    // and have other code call this class's constructor to show this form. You 
    // can also change the project properties so that it "picks" which version 
    // of main to run (see Mr. Wachs for instructions on how to do this). I  
    // have removed the main method for this class (by commenting it out below)
    ////////////////////////////////////////////////////////////////////////////
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Graphics1().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
